### ISSUE TITLE
Request to acquire Bearer token results in 502

### ISSUE THREAD

**Issue by purezen** [simplabs/rails_api_auth-demo#1]
The mentioned request to acquire a Bearer token from the Rails application to authenticate with a Facebook account leads to a "Completed 502 Bad Gateway" on the Rails end.

**Comment by oliverbarnes** [comment]
That seems to be a Facebook API error. Is it still happening? Do you have a fresh authentication code?

**Comment by marcoow** [comment]
We should log more to the Rails log [here](https://github.com/simplabs/rails_api_auth/blob/a07232b01ea930de545c632f742f073915c1fbda/app/controllers/oauth2_controller.rb#L47) so there's more info when an error like this happens.

**Comment by purezen** [comment]
@oliverbarnes Yes. Again yes, I did try with a fresh authentication code.

**Comment by oliverbarnes** [comment]
Ok, managed to reproduce the error here. Working on a fix and will add logging with it
